dist: focal
os: linux
sudo: false
language: python

addons:
  sonarcloud:
    organization: "unhaggle"

matrix:
  include:
    - env: TOXENV=django111-py36
      python: 3.6
    - env: TOXENV=django20-py36
      python: 3.6
    - env: TOXENV=django22-py310
      python: "3.10.0"
    - env: TOXENV=django32-py310
      python: "3.10.0"
    - env: TOXENV=django40-py310 SONAR_GATE=true
      python: "3.10.0"

install:
  - pip install coveralls tox

script:
  - tox
  - |
    if [ "$SONAR_GATE" = true ]; then
      coverage xml
      sonar-scanner -Dsonar.projectVersion=$(python ./setup.py --version)
    fi

after_success:
  - coveralls
